spring.application.name=BookOnlineApp

spring.datasource.url=jdbc:mysql://localhost:3306/book_online?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=Vinhthien26@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false

server.port=8080